[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
description = "Make a gratitude list using browser local storage"
edition = "2018"
license = "MIT"
name = "grats"
repository = "https://github.com/Terkwood/grats"
version = "0.1.2-a"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4.15"
js-sys = "0.3.44"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
wasm-bindgen = "0.2.67"
web-sys = "0.3.44"
yew = "0.17.3"
